name: wheel

services:
    ner-gcc-arm:
        image: ghcr.io/northeastern-electric-racing/embedded-base:main
        build: .
        network_mode: host
        privileged: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - type: bind
              source: .
              target: /home/app
        tty: true
        expose:
            - "3240"
        environment:
            - STM_TARGET_NAME=stm32f103
        

