

typedef enum {
	NONE,
	NONE2,
	NERO_BUTTON_LEFT,
	NERO_BUTTON_UP,
	NERO_BUTTON_RIGHT,
	NERO_HOME,
	NERO_BUTTON_SELECT,
	NERO_BUTTON_DOWN,
	STEERING_PADDLE_LEFT,
	STEERING_PADDLE_RIGHT,
	MAX_STEERING_BUTTONS
} steeringio_button_t;